import Providers from "@/store/provider";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import './globals.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavBar/>
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  )
}
